---
deployment:
  tasks:
    - export PUBLICPATH=/home/u1686920/public_html/registrasi/
    - export COREPATH=/home/u1686920/public_html/registrasi/ci4_core/
    - /bin/cp -R * $COREPATH
    - /bin/cp -R public/templates $PUBLICPATH
    - /bin/cp public/.htaccess $PUBLICPATH
    - /bin/cp public/favicon.ico $PUBLICPATH
    - /bin/cp public/login.js $PUBLICPATH
    - /bin/cp public/robots.txt $PUBLICPATH
    - /bin/cp public/global.js $PUBLICPATH